### ISSUE TITLE
not working example AVTransmit2 in mac os x

### ISSUE THREAD

**Issue by trankimcanh** [jitsi/libjitsi#218]
I run example: 

> ant -lib ~/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 run-example -Drun.example.name=AVTransmit2 -Drun.example.arg.line="--local-port-base=5000 --remote-host=127.0.0.1 --remote-port-base=10000"

error:

>       [java] INFO: Warming up SecureRandom...
     [java] Dec 19, 2016 2:23:32 PM org.jitsi.util.LoggerImpl log
     [java] INFO: Warming up SecureRandom finished.
     [java] Exception in thread "main" java.lang.NullPointerException: device
     [java] 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:410)
     [java] 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:365)
     [java] 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:331)
     [java] 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:299)
     [java] 	at org.jitsi.examples.AVTransmit2.start(AVTransmit2.java:120)
     [java] 	at org.jitsi.examples.AVTransmit2.main(AVTransmit2.java:351)

Can you help me fix this error, thanks !

**Comment by dylankolson** [comment]
Similar Error:

Exception in thread "main" java.lang.NullPointerException
	at org.jitsi.impl.neomedia.MediaStreamImpl.setFormat(MediaStreamImpl.java:2898)
	at org.jitsi.examples.AVTransmit2.start(AVTransmit2.java:182)
	at org.jitsi.examples.AVTransmit2.main(AVTransmit2.java:351)

**Comment by v5anyexiuluo** [comment]
> Similar Error:
> 
> Exception in thread "main" java.lang.NullPointerException
> at org.jitsi.impl.neomedia.MediaStreamImpl.setFormat(MediaStreamImpl.java:2898)
> at org.jitsi.examples.AVTransmit2.start(AVTransmit2.java:182)
> at org.jitsi.examples.AVTransmit2.main(AVTransmit2.java:351)

Have you solved this error?

**Comment by swpalmer** [comment]
It seems to die when getting a device for MEdiaType.TEXT.
I worked around that error by adding this to the loop in initialize:

```
			if (mediaType != MediaType.AUDIO && mediaType != MediaType.VIDEO)
				continue;
```

But it still doesn't work.  The VIDEO device I get is recvonly.
Not only that, but H264 doesn't seem to be supported.  It isn't returned in the array given by:

`NeomediaServiceUtils.getMediaServiceImpl().getCurrentEncodingConfiguration().getAllEncodings(MediaType.VIDEO))
`

This library is very poorly documented and supported.  As you can see by the fact that this was asked 4 years ago with no reasonable response.

**Comment by gmreddy30** [comment]
I faced the following exception. And I tried with different options for  mediaStream like mediaStream.setDirection(MediaDirection.SENDRECV);
mediaStream.setDirection(MediaDirection.SENDONLY);
but I still the exception. 

Exception in thread "main" java.lang.IllegalArgumentException: direction
	at org.jitsi.service.neomedia.AbstractMediaStream.assertDirection(AbstractMediaStream.java:106)
	at org.jitsi.impl.neomedia.MediaStreamImpl.setDirection(MediaStreamImpl.java:2834)
	at org.jitsi.examples.AVTransmit2.start(AVTransmit2.java:129)
	at org.jitsi.examples.AVTransmit2.main(AVTransmit2.java:352)
