### ISSUE TITLE
Deadlock between RTPTranslatorImpl and MediaStreamImpl

### ISSUE THREAD

**Issue by imedwei** [jitsi/libjitsi#306]
There appears to be a lock order inversion that causes a circular dependency between RTPTranslatorImpl and MediaStreamImpl.  This failure mode is fatal and we need to restart the bridge when it happens.

I like to understand the code a bit more before we attempt a fix.  Observe that the synchronization block of dynamicRTPPayloadTypes is very broad.  Could we clarify the intent of the dynamicRTPPayloadTypes lock?  A more fine grained locking would fix this deadlock.

MediaStreamImpl.addDynamicRTPPayloadType
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/MediaStreamImpl.java#L449

## Deadlocked threads:

There is an inversion in locking order which results in the deadlock.

**Thread 1**
RTPTranslatorImpl.didRead acquires read lock
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/rtp/translator/RTPTranslatorImpl.java#L594
RTCPFeedbackMessageSender. maybeStopRequesting
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/rtp/translator/RTCPFeedbackMessageSender.java#L288
MediaStreamImpl. isKeyFrame
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/MediaStreamImpl.java#L3915
MediaStreamImpl. getPayloadBlock
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/MediaStreamImpl.java#L3994
MediaStreamImpl. getDynamicRTPPayloadType acquires dynamicRTPPayloadTypes
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/MediaStreamImpl.java#L1498

**Thread 2**
MediaStreamImpl.addDynamicRTPPayloadType acquires dynamicRTPPayloadTypes
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/MediaStreamImpl.java#L482
StreamRTPManager. addFormat
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/rtp/StreamRTPManager.java#L81
RTPTranslatorImpl. addFormat acquires write lock
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/rtp/translator/RTPTranslatorImpl.java#L293

<hr>
A stacktrack from our deployed bridge on libjitsi version 891-0-gafa086b3.  We also believe this also occurs in the head of libjitsi.

```"org.jitsi.impl.neomedia.rtp.translator.PushSourceStreamImpl" #24130 daemon prio=5 os_prio=0 tid=0x00007f74f44a2000 nid=0x339f waiting for monitor entry [0x00007f73f5dd9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.jitsi.impl.neomedia.MediaStreamImpl.getDynamicRTPPayloadTypes(MediaStreamImpl.java:1503)
	- waiting to lock <0x00000006d875f710> (a java.util.HashMap)  dynamicRTPPayloadTypes
	at org.jitsi.impl.neomedia.MediaStreamImpl.isKeyFrame(MediaStreamImpl.java:3704)
	at org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender$KeyframeRequester.maybeStopRequesting(RTCPFeedbackMessageSender.java:270)
	at org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender.maybeStopRequesting(RTCPFeedbackMessageSender.java:196)
	- locked ReentrantReadWriteLock$ReadLock lock <0x00000006d644c988>
	at org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.didRead(RTPTranslatorImpl.java:594)
	at org.jitsi.impl.neomedia.rtp.translator.PushSourceStreamImpl.read(PushSourceStreamImpl.java:271)
	at net.sf.fmj.media.rtp.util.RTPPacketReceiver.transferData(RTPPacketReceiver.java:168)
	at org.jitsi.impl.neomedia.rtp.translator.PushSourceStreamImpl.run(PushSourceStreamImpl.java:328)
	at java.lang.Thread.run(Thread.java:745)


   "qtp1481451788-26965" #26965 prio=5 os_prio=0 tid=0x00007f74f5356800 nid=0x3b3e waiting on condition [0x00007f73a24a7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006d644c988> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
	at org.jitsi.impl.neomedia.rtp.translator.RTPTranslatorImpl.addFormat(RTPTranslatorImpl.java:293)
	at org.jitsi.impl.neomedia.rtp.StreamRTPManager.addFormat(StreamRTPManager.java:118)
	at org.jitsi.impl.neomedia.MediaStreamImpl.addDynamicRTPPayloadType(MediaStreamImpl.java:494)
	- locked <0x00000006d875f710> (a java.util.HashMap)   dynamicRTPPayloadTypes
	at org.jitsi.videobridge.RtpChannel.setPayloadTypes(RtpChannel.java:1363)
	at org.jitsi.videobridge.VideoChannel.setPayloadTypes(VideoChannel.java:867)
	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:942)
   ...```

**Comment by bgrozev** [comment]
Hi and thank you for the report!

As far as I know the lock on dynamicRTPPayloadTypes is only used to ensure a consistent state of the map. So reading from it without the need to acquire a lock (e.g. if we make it copy on write) would be OK. 

I hope this helps, but note that I haven't looked at the code carefully.
