### ISSUE TITLE
Thread leak

### ISSUE THREAD

**Issue by shijir38** [jitsi/libjitsi#377]
Hello guys,

I am making an IVR system for my own pet project. And umm I've encountered a thread leak.

"RTCP Reporter" #4894 daemon prio=9 os_prio=0 tid=0x00007fdeb8074000 nid=0x5029 in Object.wait() [0x00007fde35ad7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at net.sf.fmj.media.rtp.RTCPReporter.run(RTCPReporter.java:75)
        - locked <0x000000077be442b0> (a net.sf.fmj.media.rtp.util.RTPMediaThread)
        at java.lang.Thread.run(Thread.java:748)
        at net.sf.fmj.media.util.MediaThread.run(MediaThread.java:202)

Anyone encountered this before?

**Comment by shijir38** [comment]
It seems in a highly concurrent application, Creating and closing lots of media streams result in a thread leak. I fixed this by making the clean up process single threaded.
