### ISSUE TITLE
NPE with new RetransmissionRequesterDelegate Refactor

### ISSUE THREAD

**Issue by imedwei** [jitsi/libjitsi#402]
I'm not entirely sure this isn't my fault but just wanted to give you a heads up that I am seeing NPEs being thrown by the new RetransmissionRequesterDelegate refactor.

```
Feb 13, 2018 11:06:46 PM org.jitsi.util.LoggerImpl log
SEVERE: The invocation of the method org.jitsi.impl.neomedia.transform.RetransmissionRequesterDelegate.run() threw an exception.
java.lang.NullPointerException
	at org.jitsi.impl.neomedia.transform.RetransmissionRequesterDelegate$Requester.notifyNackCreated(RetransmissionRequesterDelegate.java:485)
	at org.jitsi.impl.neomedia.transform.RetransmissionRequesterDelegate.createNackPackets(RetransmissionRequesterDelegate.java:312)
	at org.jitsi.impl.neomedia.transform.RetransmissionRequesterDelegate.run(RetransmissionRequesterDelegate.java:175)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```

**Comment by imedwei** [comment]
@bbaldino ^

**Comment by bgrozev** [comment]
I also see some of these on beta. Perhaps because the lock used for 'requests' is released between lines 304 and 312?

**Comment by bbaldino** [comment]
What happens when this occurs?  Does it break everything or is it somewhat harmless?  I'll try and take a look but I don't think it'll be soon.

**Comment by bgrozev** [comment]
Just looking at the code I think it would fail to send a NACK when the condition occurs, but it should immediately run again because the exception prevents nextRequestAt from being updated. So mostly harmless, I think.
