### ISSUE TITLE
Unable to load library jnmaccoreaudio

### ISSUE THREAD

**Issue by nabhonil** [jitsi/libjitsi#557]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Unable to load library jnmaccoreaudio whereas other libraries are getting loaded properly.

## Current behavior
I am trying to create an application to stream audio. So whenever i use the following code 
LibJitsi.start();
MediaService mediaService = LibJitsi.getMediaService();

I get the below exception which shows issues with loading library jnmaccoreaudio. As you can see the other dylib files are properly loaded and not throwing any exception whereas only jnmaccoreaudio is throwing the exception. Any idea if i am missing any thing here.

Exception is shown below:-
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Successfully started LibJitsi using as implementation: org.jitsi.impl.libjitsi.LibJitsiImpl
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: java.runtime.name=Java(TM) SE Runtime Environment
sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib
java.vm.version=25.321-b07
gopherProxySet=false
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=IN
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification
java.runtime.version=1.8.0_321-b07
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/endorsed
os.arch=x86_64
java.io.tmpdir=/var/folders/jc/v97_thqx50jfmtw28_dh586m0000gn/T/
line.separator=

net.sf.fmj.utility.JmfRegistry.disableLoad=true
java.vm.specification.vendor=Oracle Corporation
os.name=Mac OS X
sun.jnu.encoding=UTF-8
java.library.path=syslib/darwin
java.specification.name=Java Platform API Specification
java.class.version=52.0
org.jitsi.service.audionotifier.AudioNotifierService=org.jitsi.impl.neomedia.notify.AudioNotifierServiceImpl
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=12.3.1
http.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
user.home=/Users/nasinha
user.timezone=Asia/Kolkata
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/bin:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jtapi.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jtracing.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/org.jlibrtp-0.2.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/CiscoJCEProvider.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jitsi-utils-1.0-112-gd92472a.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/libjitsi-1.1-4-gfb6b03ff.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jitsi-lgpl-dependencies-1.2-15-g79dec2d.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/fmj-1.0.2-jitsi.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/bcpkix-jdk15on-1.70.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/bcprov-jdk15on-1.70.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/bctls-jdk15on-1.70.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/commons-lang3-3.12.0.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/java-sdp-nist-bridge-1.2.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jitsi-srtp-1.1-5-g70395c7.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/jna-5.11.0.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/json-simple-1.1.1.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/sdes4j-1.1.5.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/zrtp4j-light-4.1.2.jar:/Users/nasinha/Workspaces/EclipseWorkspace/CiscoDeviceNotification/lib/kotlin-runtime-1.2.71.jar
user.name=nasinha
java.vm.specification.version=1.8
sun.java.command=com.cisco.ccm.jtapi.client.CiscoDeviceNotificationReceiver
java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
net.sf.fmj.utility.JmfRegistry.disableCommit=true
awt.toolkit=sun.lwawt.macosx.LWCToolkit
java.vm.info=mixed mode
java.version=1.8.0_321
java.ext.dirs=/Users/nasinha/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
sun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/jre/classes
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeBig
sun.cpu.endian=little
socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16
ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
sun.cpu.isalist=

Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Normal classloader
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: failed to find jitsi-defaults.properties with class loader, will continue without it.
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Normal classloader
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: failed to find jitsi-default-overrides.properties with class loader, will continue without it.
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnopus from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnspeex from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Initializing audio devices
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnmaccoreaudio from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
WARNING: Failed to initialize org.jitsi.impl.neomedia.device.MacCoreaudioSystem
java.lang.UnsatisfiedLinkError: org.jitsi.impl.neomedia.device.MacCoreAudioDevice.getDefaultInputDeviceUIDBytes()[B
	at org.jitsi.impl.neomedia.device.MacCoreAudioDevice.getDefaultInputDeviceUIDBytes(Native Method)
	at org.jitsi.impl.neomedia.device.MacCoreAudioDevice.getDefaultInputDeviceUID(MacCoreAudioDevice.java:75)
	at org.jitsi.impl.neomedia.device.MacCoreaudioSystem.doInitialize(MacCoreaudioSystem.java:122)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initialize(DeviceSystem.java:641)
	at org.jitsi.impl.neomedia.device.DeviceSystem.invokeDeviceSystemInitialize(DeviceSystem.java:446)
	at org.jitsi.impl.neomedia.device.DeviceSystem.invokeDeviceSystemInitialize(DeviceSystem.java:349)
	at org.jitsi.impl.neomedia.device.DeviceSystem.<init>(DeviceSystem.java:494)
	at org.jitsi.impl.neomedia.device.AudioSystem.<init>(AudioSystem.java:204)
	at org.jitsi.impl.neomedia.device.AudioSystem2.<init>(AudioSystem2.java:81)
	at org.jitsi.impl.neomedia.device.MacCoreaudioSystem.<init>(MacCoreaudioSystem.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:289)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:231)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:161)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:348)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:163)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:170)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:122)
	at com.cisco.ccm.jtapi.client.CiscoRTPOutputStartedEvActionImpl.action(CiscoRTPOutputStartedEvActionImpl.java:69)
	at com.cisco.ccm.jtapi.client.CiscoDeviceNotificationProcessor.run(CiscoDeviceNotificationProcessor.java:42)
	at java.lang.Thread.run(Thread.java:750)

Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnportaudio from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Initializing video devices
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnquicktime from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for FaceTime HD Camera (Built-in):java.awt.Dimension[width=640,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for FaceTime HD Camera (Built-in):java.awt.Dimension[width=640,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for FaceTime HD Camera (Built-in):java.awt.Dimension[width=1280,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for FaceTime HD Camera (Built-in):java.awt.Dimension[width=1280,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=160,height=120]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=160,height=120]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=320,height=240]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=320,height=240]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=432,height=240]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=432,height=240]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=544,height=288]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=544,height=288]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=640,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=640,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=800,height=600]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=800,height=600]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=864,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=864,height=480]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=960,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=960,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1024,height=576]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1024,height=576]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1280,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1280,height=720]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1920,height=1080]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Webcam available resolution for Lenovo FHD Webcam:java.awt.Dimension[width=1920,height=1080]
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Looking for configured audio devices.
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Scanning for configured Video Devices.
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Found FaceTime HD Camera (Built-in) as a AVFRAME, class org.jitsi.impl.neomedia.codec.video.AVFrame video capture device.
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnawtrenderer from java.library.path rather than bundled version
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Warming up SecureRandom...
Apr 10, 2022 8:39:54 AM org.jitsi.utils.logging.LoggerImpl log
INFO: Warming up SecureRandom finished.

## Expected Behavior
No exception should be thrown

## Possible Solution
Not known yet.

## Steps to reproduce
Start writing a libjitsi application. Use the following code on a mac laptop:-
LibJitsi.start();
MediaService mediaService = LibJitsi.getMediaService();

# Environment details
Mac Laptop Latest OS 12.3.1

**Comment by nabhonil** [comment]
Tried out a similar setup on a windows 10 enterprise edition and getting the similar error 
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Successfully started LibJitsi using as implementation: org.jitsi.impl.libjitsi.LibJitsiImpl
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: java.runtime.name=Java(TM) SE Runtime Environment
sun.boot.library.path=C:\Program Files\Java\jre1.8.0_321\bin
java.vm.version=25.321-b07
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=;
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
user.script=
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=
java.vm.specification.name=Java Virtual Machine Specification
user.dir=C:\RoboCall
java.runtime.version=1.8.0_321-b07
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_321\lib\endorsed
os.arch=amd64
java.io.tmpdir=C:\Users\root\AppData\Local\Temp\
line.separator=

net.sf.fmj.utility.JmfRegistry.disableLoad=true
java.vm.specification.vendor=Oracle Corporation
user.variant=
os.name=Windows 10
sun.jnu.encoding=Cp1252
java.library.path=C:\RoboCall\win32-x86-64
java.specification.name=Java Platform API Specification
java.class.version=52.0
org.jitsi.service.audionotifier.AudioNotifierService=org.jitsi.impl.neomedia.notify.AudioNotifierServiceImpl
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=10.0
user.home=C:\Users\root
user.timezone=Asia/Calcutta
java.awt.printerjob=sun.awt.windows.WPrinterJob
file.encoding=Cp1252
java.specification.version=1.8
java.class.path=.\cdn-nabhonil.jar
user.name=root
java.vm.specification.version=1.8
sun.java.command=.\cdn-nabhonil.jar
java.home=C:\Program Files\Java\jre1.8.0_321
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
net.sf.fmj.utility.JmfRegistry.disableCommit=true
awt.toolkit=sun.awt.windows.WToolkit
java.vm.info=mixed mode
java.version=1.8.0_321
java.ext.dirs=C:\Program Files\Java\jre1.8.0_321\lib\ext;C:\Windows\Sun\Java\lib\ext
sun.boot.class.path=C:\Program Files\Java\jre1.8.0_321\lib\resources.jar;C:\Program Files\Java\jre1.8.0_321\lib\rt.jar;C:\Program Files\Java\jre1.8.0_321\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_321\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_321\lib\jce.jar;C:\Program Files\Java\jre1.8.0_321\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_321\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_321\classes
java.vendor=Oracle Corporation
sun.stderr.encoding=cp437
file.separator=\
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
sun.stdout.encoding=cp437
sun.desktop=windows
sun.cpu.isalist=amd64

Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Normal classloader
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: failed to find jitsi-defaults.properties with class loader, will continue without it.
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Normal classloader
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: failed to find jitsi-default-overrides.properties with class loader, will continue without it.
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnopus from java.library.path rather than bundled version
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnspeex from java.library.path rather than bundled version
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Initializing audio devices
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnwasapi from java.library.path rather than bundled version
Apr 11, 2022 9:40:19 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnportaudio from java.library.path rather than bundled version
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jnwincoreaudio from java.library.path rather than bundled version
initDevices (coreaudio/device.c):
        CoInitialize
getDevice (coreaudio/device.c):
        IMMDeviceEnumerator.GetDevice
getDeviceProperty (coreaudio/device.c):
        getDevice
getDeviceModelIdentifier (coreaudio/device.c):
        getDeviceDescription
getDevice (coreaudio/device.c):
        IMMDeviceEnumerator.GetDevice
getDeviceProperty (coreaudio/device.c):
        getDevice
getDeviceModelIdentifier (coreaudio/device.c):
        getDeviceDescription
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Initializing video devices
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Loading library jndirectshow from java.library.path rather than bundled version
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Looking for configured audio devices.
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Scanning for configured Video Devices.
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Found Desktop Streaming 0 as a AVFRAME, class org.jitsi.impl.neomedia.codec.video.AVFrame video capture device.
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
SEVERE: Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
java.lang.UnsatisfiedLinkError: Directory separator should not appear in library name: C:\Users\root\AppData\Local\Temp\jna-3506402\jna4373650608101564420.dll
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:151)
        at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:103)
        at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:50)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:101)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1045)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:366)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:163)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:170)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:122)
        at com.cisco.ccm.jtapi.client.CiscoRTPOutputStartedEvActionImpl.action(CiscoRTPOutputStartedEvActionImpl.java:69)
        at com.cisco.ccm.jtapi.client.CiscoDeviceNotificationProcessor.run(CiscoDeviceNotificationProcessor.java:42)
        at java.lang.Thread.run(Unknown Source)

Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Warming up SecureRandom...
Apr 11, 2022 9:40:20 PM org.jitsi.utils.logging.LoggerImpl log
INFO: Warming up SecureRandom finished.

Is anything I am missing out ?

**Comment by nabhonil** [comment]
I am able to solve the problem in windows. I have downloaded the libjitsi bundle from mvnrepository.com and from the bundle i have extracted the native dlls present under the win32_x86-64. I have kept them in a folder named C:\Jitsi\win32_x86-64\(all dlls are kept here). In the Advanced System settings of windows and in the System Path Environment Variables i have added this path C:\Jitsi\win32_x86-64. After this whenever i run my application runnable jar, I run it from command prompt in the following way "java "-Djava.library.path=C:\Jitsi\win32_x86-64" -jar MyApplication..jar.

Now in my code where I am calling
LibJitsi.start();
MediaService mediaService = LibJitsi.getMediaService();

I dont get any error(as mentioned above) in Windows system now. I am using Windows 2019 server 64 bit.

**Comment by irfanbacker-cisco** [comment]
I'm facing the same issue in Mac. I resolved it by extracting the .dylib files and adding its location to the class path. Looks like the dynamic loading of bundled libraries are not working.
